version: "2"
services:
    fanshop-nginx:
        build: "./.docker/nginx-ubuntu/"
        container_name: "fanshop-nginx"
        domainname: spryker-fanshop.dev
        volumes_from:
          - "fanshop-php"
        ports:
          - "80:80"
          - "443:443"
        networks:
          fanshop_net:
            ipv4_address: 172.20.0.3

    fanshop-postgresql-db:
        image: postgres
        container_name: fanshop-postgresql-db
        expose:
            - "5432"
        ports:
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: mate20mg
            POSTGRES_DB: fanshop_db
            POSTGRES_USER: development
        networks:
          fanshop_net:
            ipv4_address: 172.20.0.4

    fanshop-php:
        build:
          context: ./.docker/php-ubuntu/
        container_name: "fanshop-php"
        volumes:
          - .:/var/www/html
        expose:
          - "9000"
        networks:
          fanshop_net:
            ipv4_address: 172.20.0.5

    fanshop-mailcatcher:
        container_name: fanshop-mailcatcher
        image: schickling/mailcatcher
        ports:
            - "1025:1025"
            - "1080:1080"
        networks:
          fanshop_net:
            ipv4_address: 172.20.0.6

    fanshop-elasticsearch:
        build: "./.docker/elasticsearch/"
        container_name: "fanshop-elasticsearch"
        networks:
          fanshop_net:
            ipv4_address: 172.20.0.8

    fanshop-redis:
        image: "redis:alpine"
        container_name: "fanshop-redis"
        networks:
          fanshop_net:
            ipv4_address: 172.20.0.9

    fanshop-jenkins:
        image: "jenkinsci/jenkins"
        container_name: "fanshop-jenkins"
        expose:
          - "8080"
        networks:
          fanshop_net:
            ipv4_address: 172.20.0.10


networks:
  fanshop_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1